/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_serce_panex_ChecksumBenchmark */

#ifndef _Included_me_serce_panex_ChecksumBenchmark
#define _Included_me_serce_panex_ChecksumBenchmark
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     me_serce_panex_ChecksumBenchmark
 * Method:    nativePlainChecksum
 * Signature: (JI)V
 */
JNIEXPORT jint JNICALL Java_me_serce_panex_ChecksumBenchmark_nativePlainChecksum
  (JNIEnv *, jclass, jlong, jint);

JNIEXPORT jint JNICALL JavaCritical_me_serce_panex_ChecksumBenchmark_nativePlainChecksum
(jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
