/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <cstring>
#include <cstdio>

#include "checksum.h"

JNIEXPORT jint JNICALL Java_me_serce_panex_ChecksumBenchmark_nativePlainChecksum
    (JNIEnv * env, jclass clz, jlong addr, jint targetLength) {
    char *target = reinterpret_cast<char *>(addr);
    unsigned int checksum = 0;
    for (int i = 0; i < targetLength; ++i) {
        checksum += (unsigned int) target[i];
    }
    return checksum % 256;
}

JNIEXPORT jint JNICALL JavaCritical_me_serce_panex_ChecksumBenchmark_nativePlainChecksum
    (jlong addr, jint targetLength) {
    char *target = reinterpret_cast<char *>(addr);
    unsigned int checksum = 0;
    for (int i = 0; i < targetLength; ++i) {
        checksum += (unsigned int) target[i];
    }
    return checksum % 256;
}


JNIEXPORT jint JNICALL Java_me_serce_panex_ChecksumBenchmark_sum_1native
    (JNIEnv * env, jclass clz, jint a, jint b, jint c) {
    return a+b+c;
}

JNIEXPORT jint JNICALL JavaCritical_me_serce_panex_ChecksumBenchmark_sum_1native
    (jint a, jint b, jint c) {
    a = 0;
    b = 0;
    return a/b;
}